-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.staff
(
    staff_id integer NOT NULL,
    first_name character varying(25) NOT NULL,
    last_name character varying(25) NOT NULL,
    "position" character varying,
    start_date date,
    location character varying(10),
    PRIMARY KEY (staff_id)
);

CREATE TABLE IF NOT EXISTS public.sales_outlet
(
    sales_outlet_id integer NOT NULL,
    sales_outlet_type character varying(25),
    address character varying(40) NOT NULL,
    city character varying(25) NOT NULL,
    telephone character varying(15),
    postal_code integer,
    manager integer,
    PRIMARY KEY (sales_outlet_id)
);

CREATE TABLE IF NOT EXISTS public.sales_transaction
(
    transaction_id integer NOT NULL,
    transaction_date date,
    transaction_time time(6) without time zone,
    sales_outlet_id integer NOT NULL,
    staff_id integer NOT NULL,
    customer_id integer,
    product_id integer NOT NULL,
    quantity integer NOT NULL,
    price character(4),
    PRIMARY KEY (transaction_id)
);

CREATE TABLE IF NOT EXISTS public.customer
(
    customer_id integer NOT NULL,
    customer_name character varying(30),
    customer_email character varying(30) NOT NULL,
    customer_since date,
    customer_card_number character(12),
    birthdate date,
    gender character(1),
    PRIMARY KEY (customer_id)
);

CREATE TABLE IF NOT EXISTS public.product
(
    product_id integer NOT NULL,
    product_category character(25) NOT NULL,
    product_type character varying(30),
    product_name character varying(25),
    description character varying(150),
    price character varying(4) NOT NULL,
    PRIMARY KEY (product_id)
);
END;